### PR TITLE
Separate

### PR DESCRIPTION
**Pull request by SourceZh**
I have remove the **getnode** from etcblib.py, and there is no method in etcblib.py that can help me to get the key in etcb(the method **getkey** in etcblib.py in fact gets the value in etcb). So I write the method **generatekey** in worker to simulate etcb to generate the key manually.

### CODE REVIEW

**Comment by caodg** [comment]
Cool! 

@leebaok , maybe in the future we need to refactor etcdlib, **getkey** changed to **getvalue**, and add a new method named **getkey** ?

**Comment by leebaok** [comment]
@SourceZh 

Close to success !

I tested restarting master without stopping workers and starting master and workers in 'start' mode. They work well.

But for **init** mode of startup, there is a bug. In worker.py, you set key of runnodes/IP to 'waitting' in line 57 and than test key of runnodes/IP in line 78. Of cause, it exists and the mode is always recovery. 

I think you can use allnodes/IP to decide the mode. For example, self.key in line 60 is sat to allnodes/IP and etcd.listdir in line 76 is to get content of 'machines/allnodes'. 

What do you think ?

**Comment by caodg** [comment]
@leebaok
It will be perfect if the separate starting of master and slave works in both **recovery** mode and **init** mode. But in most cases, we will not init an already running system. If we have to init the master, it seems reasonable to restart all workers.
Therefore, I recommend we accept and merge this pull request, but stating that there is still a small problem left. Maybe we can open another issue and expecting @SourceZh submit a succeeding pull requests?

**Comment by leebaok** [comment]
OK. 

@SourceZh 

Hope your next pull request to repair the **init mode** of startup !

**Comment by caodg** [comment]
congratulations, and thank you very much! @SourceZh

**Comment by leebaok** [comment]
Thank you for your contribution ! @SourceZh

**Pull request merged**
