### PR TITLE
Fix a bug in monitor.py, which may stop the thread.

### PR DESCRIPTION
**Pull request by FirmlyReality**

### CODE REVIEW

**Comment by caodg** [comment]
I noticed that you have hardcoded the docklet running dir in source code, which should also be fixed.

```
if(part.mountpoint.startswith('/opt/docklet/local/volume')):
```

**Comment by caodg** [comment]
@leebaok ， should we accept this request first to make it work in the default setting, or ask @FirmlyReality withdraw and resubmit a complete solution?

**Comment by leebaok** [comment]
@caodg 

I think we can accept the pull request first to fix the hot bug. And the hardcoded path could be fix later.

**Comment by leebaok** [comment]
@caodg 
So I merge the pull request and I will deploy the latest code on iwork tomorrow.

**Pull request merged**
